version: '1.0'
services:
  postgresql:
    image: postgis/postgis:latest
    container_name: postgis
    environment:
      POSTGRES_DB: ${POSTGRES_DB}  # Имя вашей базы данных
      POSTGRES_USER: ${POSTGRES_USER}    # Имя пользователя базы данных
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Пароль пользователя базы данных
    ports:
      - 5432:5432  # Маппинг портов (локальный порт: порт в контейнере)
    volumes:
      - /path/to/local/data:/var/lib/postgresql/data  # Монтирование тома для сохранения данных

  favorite-service:
    image: favorite-service:1.0
    ports:
      - "5001:5001"
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}

  apartment-service:
    image: apartment-service:1.0
    ports:
      - "5002:5002"
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}


volumes:
  postgres_data: